name: Test Rust project

on:
  workflow_call:
    inputs:
      apt_packages:
        required: false
        type: string
      msrv:
        required: false
        type: string
        default: "1.57.0"
    secrets:
      github-token:
        required: false

env:
  RUSTFLAGS: '-Dwarnings'
  # disable incremental compilation.
  #
  # incremental compilation is useful as part of an edit-build-test-edit cycle,
  # as it lets the compiler avoid recompiling code that hasn't changed. however,
  # on CI, we're not making small edits; we're almost always building the entire
  # project from scratch. thus, incremental compilation on CI actually
  # introduces *additional* overhead to support making future builds
  # faster...but no future builds will ever occur in any given CI environment.
  #
  # see https://matklad.github.io/2021/09/04/fast-rust-builds.html#ci-workflow
  # for details.
  CARGO_INCREMENTAL: 0
  # allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). this should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short

jobs:
  check-msrv:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
          - windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707 # tag = v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1ce4a7352a1efe5dede2e52c75512b34256e4f44 # tag=v1
      with:
        toolchain: ${{ inputs.msrv }}

    - uses: Swatinem/rust-cache@b894d59a8d236e2979b247b80dac8d053ab340dd # tag=v2.1.0
      with:
        key: cargo-cache-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}-${{ matrix.os }}

    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # tag=v1
      with:
        crate: cargo-hack

    - name: Test compilation
      run: cargo hack check --each-feature

  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2
    - uses: EmbarkStudios/cargo-deny-action@7257a18a9c2fe3f92b85d41ae473520dff953c97 # tag=v1
      with:
        command: check ${{ matrix.checks }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
          - windows-2022
        rust:
          - beta
          - nightly
          - stable

    steps:
    - name: Checkout repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

    - uses: rui314/setup-mold@b2554ccb6486461b7022f149ac59c96757fd8dee # v1
      if: runner.os == 'Linux'
      with:
        make-default: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1ce4a7352a1efe5dede2e52c75512b34256e4f44 # tag=v1
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt

    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # tag=v1
      with:
        crate: cargo-nextest

    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@bf6758885262d0e6f61089a9d8c8790d3ac3368f # tag=v1
      with:
        crate: cargo-hack

    - uses: Swatinem/rust-cache@b894d59a8d236e2979b247b80dac8d053ab340dd # tag=v2.1.0
      with:
        key: cargo-cache-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}-${{ matrix.os }}-${{ matrix.rust }}

    - name: Install required packages (Linux)
      if: ${{ inputs.apt_packages != '' && runner.os == 'Linux' }}
      shell: bash
      env:
        PACKAGES: ${{ inputs.apt_packages }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${PACKAGES}

    - name: Check formatting
      shell: bash
      run: cargo fmt -- --check

    - name: Setup Embark Studios lint rules
      shell: bash
      run: |
        mkdir .cargo
        curl -sL https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/lints.toml > .cargo/config.toml

    - name: Clippy
      shell: bash
      run: cargo clippy

    - name: Test compilation
      run: cargo hack check --each-feature

    - name: Run tests
      shell: bash
      run: cargo nextest run --all-features
