name: Test Nix Flakes project

on:
  workflow_call:
    inputs:
      extra-targets:
        type: string
        required: false
        default: ""
      extra-nix-flags:
        type: string
        required: false
        default: ""
    secrets:
      cachix-token:
        required: true
      github-token:
        required: true

jobs:
  check:
    name: Build and check
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@07b8bcba1b22d847db7ee507180c33e115499665 # v8

    - name: Set up Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2

    - name: Set up Cachix (msfjarvis)
      uses: cachix/cachix-action@6a2e08b5ebf7a9f285ff57b1870a4262b06e0bee # v13
      with:
        name: msfjarvis
        authToken: ${{ secrets.cachix-token }}
        cachixArgs: -c9 --omit-deriver

    - name: Run default check
      shell: bash
      env:
        NIX_FLAGS: ${{ inputs.extra-nix-flags }}
      run: |
        read -ra FLAGS <<<"$NIX_FLAGS"
        nix flake check --print-build-logs "${FLAGS[@]}"

    - name: Run additional checks
      shell: bash
      if: ${{ inputs.extra-targets != '' }}
      env:
        TARGET_STRING: ${{ inputs.extra-targets }}
        NIX_FLAGS: ${{ inputs.extra-nix-flags }}
      run: |
        read -ra TARGETS <<<"$TARGET_STRING"
        read -ra FLAGS <<<"$NIX_FLAGS"
        for TARGET in "${TARGETS[@]}"; do
          nix build --print-build-logs "${FLAGS[@]}" "${TARGET}"
        done
