name: Test Nix Flakes project

on:
  workflow_call:
    inputs:
      extra-targets:
        type: string
        required: false
        default: ""
      # No idea where this is used, choosing to ignore it.
      extra-nix-flags:
        type: string
        required: false
        default: ""
    secrets:
      cachix-token:
        required: false
      github-token:
        required: true

jobs:
  check:
    name: Build and check
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: 'recursive'
        persist-credentials: false

    - name: Install Nix
      shell: bash
      run: |
        if [[ -z $(command -v nix) ]]; then
          curl --proto '=https' --tlsv1.2 -sSf -L https://nixos.org/nix/install | sh -s -- --daemon --yes
          {
            echo "access-tokens = github.com=$GITHUB_TOKEN"
            echo "experimental-features = nix-command flakes"
          } | sudo tee -a /etc/nix/nix.conf > /dev/null
          echo /nix/var/nix/profiles/default/bin >> "$GITHUB_PATH"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run default check
      shell: bash
      run: |
        nix profile install github:NixOS/nixpkgs/nixpkgs-unstable#nix-fast-build
        export PATH="$HOME/.nix-profile/bin:$PATH"
        nix-fast-build --flake ".?submodules=1#checks.$(nix eval --raw --impure --expr builtins.currentSystem)" --no-nom --fail-fast

    - name: Run additional checks
      shell: bash
      if: ${{ inputs.extra-targets != '' }}
      env:
        TARGET_STRING: ${{ inputs.extra-targets }}
        NIX_FLAGS: ${{ inputs.extra-nix-flags }}
      run: |
        read -ra TARGETS <<<"$TARGET_STRING"
        read -ra FLAGS <<<"$NIX_FLAGS"
        for TARGET in "${TARGETS[@]}"; do
          nix build --print-build-logs "${FLAGS[@]}" "${TARGET}"
        done
