name: Test Rust project

on:
  workflow_call:
    inputs:
      apt_packages:
        required: false
        type: string
    secrets:
      github-token:
        required: false

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  index:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate LSIF data
        uses: sourcegraph/lsif-rust-action@main
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-20.04
          - windows-2022
        rust:
          - beta
          - nightly
          - stable

    steps:
    - name: Checkout repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Install Rust toolchain (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run:
        curl https://sh.rustup.rs -sSf | sh -s -- --profile default --default-toolchain ${{ matrix.rust }} -y

    - name: Install rust toolchain (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -o rustup-init.exe
        ./rustup-init --profile default --default-toolchain ${{ matrix.rust }} -y

    - name: Cache cargo registry and build outputs
      uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}

    - name: Check formatting
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: fmt
        args: -- --check

    - name: Install required packages (Linux)
      if: ${{ inputs.apt_packages != '' && runner.os == 'Linux' }}
      shell: bash
      env:
        PACKAGES: ${{ inputs.apt_packages }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${PACKAGES}

    - name: Run cargo check
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: check
        args: --all-features

    - name: Run cargo clippy
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: clippy

    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        version: "0.9.2"

    - name: Run cargo nextest
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: nextest
        args: run --all-features

    - name: Install cargo-deny
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-deny
        version: "0.11.3"

    - name: Run cargo deny
      shell: bash
      run: |
        if [ -f deny.toml ]; then
          cargo deny check
        fi
