name: Test Nix Flakes project

on:
  workflow_call:
    inputs:
      extra-targets:
        type: string
        required: false
        default: ""
    secrets:
      cachix-token:
        required: true
      github-token:
        required: true

jobs:
  check:
    name: Build and check
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

    - name: Install Nix
      uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.github-token }}

    - name: Set up Cachix (msfjarvis)
      uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f # tag=v12
      with:
        name: msfjarvis
        authToken: ${{ secrets.cachix-token }}
        cachixArgs: -c9 --omit-deriver

    - name: Run default check
      shell: bash
      run: |
        nix flake check --print-build-logs

    - name: Run additional checks
      shell: bash
      if: ${{ inputs.extra-targets != '' }}
      env:
        TARGET_STRING: ${{ inputs.extra-targets }}
      run: |
        read -ra TARGETS <<<"$TARGET_STRING"
        for TARGET in "${TARGETS[@]}"; do
          nix build --print-build-logs "${TARGET}"
        done
